version: '3.1'
services:
  web: 
    build: .
    environment:
      DB_HOST: "mongo"
      DB_PORT: 27017
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
      KEY: "b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcnNhAAAAAwEAAQAAAYEAzsHl2rL66pIXJs9DDZVvsE8F4pEgsz49e7ypNWZC6GtFKctsCMUF3OYfvp1Ad0gf70cysOMiHjiNe8w3MakiAkM4mC6p4zoo5DHWBwwBbtoo3L6K0CbBRxqtrp6zmjsV0Y3Kl3qrpvw1+BkzCcUwGDzsSelNcCtyMiugxxbEON0vmt0GOMqVZXFCexfubFM91LZ1wq5kcboOULmPAqKAmZFFJmXwLuYozDxuOcPgTa3pDWZUJrPAAkjd1CdUwvRTM7u33xnYyJRTlvV/IXN1VeIYtMWmeJwrcextBYlcM8ekSpOtJO3nMtaKodaGallj8by5MCdBlWSou2GYCI1TDpAeZvttIqyn9RbRdRYUdVhzXDQ1ySXIuOs5AE4o3y0BjDdHxILJG5l3ukmeqYpZomyw4c6jgn186Xguy2AaCEdmWB+Z3Nf0EWKKqMFjDFtkXV72ouA7eUE4PfNt+n+606YouPESpfdc+1ZkDGcptr9KWm0hj4XbrlUDRMOnti6FAAAFkHBx61JwcetSAAAAB3NzaC1yc2EAAAGBAM7B5dqy+uqSFybPQw2Vb7BPBeKRILM+PXu8qTVmQuhrRSnLbAjFBdzmH76dQHdIH+9HMrDjIh44jXvMNzGpIgJDOJguqeM6KOQx1gcMAW7aKNy+itAmwUcara6es5o7FdGNypd6q6b8NfgZMwnFMBg87EnpTXArcjIroMcWxDjdL5rdBjjKlWVxQnsX7mxTPdS2dcKuZHG6DlC5jwKigJmRRSZl8C7mKMw8bjnD4E2t6Q1mVCazwAJI3dQnVML0UzO7t98Z2MiUU5b1fyFzdVXiGLTFpnicK3HsbQWJXDPHpEqTrSTt5zLWiqHWhmpZY/G8uTAnQZVkqLthmAiNUw6QHmb7bSKsp/UW0XUWFHVYc1w0NcklyLjrOQBOKN8tAYw3R8SCyRuZd7pJnqmKWaJssOHOo4J9fOl4LstgGghHZlgfmdzX9BFiiqjBYwxbZF1e9qLgO3lBOD3zbfp/utOmKLjxEqX3XPtWZAxnKba/SlptIY+F265VA0TDp7YuhQAAAAMBAAEAAAGAE4ZyG3Ydhftn3k1iaqz7EC5WQvAro2G0UrQdUqKmnOZMcMb6G9XnWNYOl2SoSttv0JvrqJK6jRoQGmnNqI3tXUNV2+FEP+YlKG+gY6f5lqtZgocn+sI+LGXTkxL/qQf9Zn26bRWzkiBtRFG05S5O/Wr7cXtrybUAosZF96cpvqj8ruZCiShwdVT9zzwSUv6Fb0oP0uO/LpJAedUcMUaBWH9EhXzI8tTfc3Idgq0ByLQstww71C/TaSPSdw+DzKlf6qJKM4u6I3Ch0OctgfPLfqCxiCG5qQYz+Qcd/q938KUwwSr45qLR/X2XiFEa46O2+bJ7MuAEtXI82QLRJ7GrHPnlL5k/jkxn2iYLC221qQ6Vvp58IOYmRYvwLFVOJY1Ia1vSURKA5D0AFLVFkxejOzs7ardkcdqRaTnDQaZRnw9aJCVJN5HTsQDbKBozsWGP78owreJoLiNNXmoJv7ZxnTW8gi3azxXTMc7FbDtxIzBO7Yt5HxcD/t5ShcZW/okdAAAAwGWiU6AFF2aQb3F1ypTnM0WgKu/whKxL5qgiREO8KKgt6KQKzsczZCFJRii43Z+ju9xf8RBHDMeBwqFz25wvkKQ2WZ5pujXM+A6sGJ31mqJDRMoREagiG81nvKe/0tdbDw4aAowtl1NCXarB1bYdwApqItusgTQgd2LRK8EY16Yut7HofQx0aYudme0+tdWjndoc6/GA+B9fi3oExywVx6LdGov5ez6KPSkqUYsQmcEJvLzy8TJpfp1JG6U/J47gtQAAAMEA6+VWJJ9aJs9K45nluJOzsp16+lQaFyTGu88MKnlzSV4v3xuhtSFZnU20KxdirF4wFlaVEhYIEZYB/B92uYTJcUu3BaiWQbI+1+q6quX8MyxxfjL9P212BU/bSgdlMZjn4Km/QsrqrAq/WjA65batAowacOLHvS6d4roUd69urVCi4StlvkJRgXDS4limPRd5YXOmWWokaa0SZHj8HveF7ctP1mhSDpA5k2tjPJwyyRVuJPf22hr/u5V68/CeRsn7AAAAwQDgYNU5A1bAGUgBnkK0uProtb1BMiV6ahMMxJxi4aOrCY6hK5oIm6026WEzlkOFH17RHzTleQX/chE0/klpDvT3xUlUZnB7JG4N/v6dJygRrvkW8/6yFFmpy4ZnFiRkbgFninxZpO0BqJnHPuUYHghqf7p4lN0quzuwiI7qBf3RozNVOY43MbCCRYOd+2FfKLqS7s9lAYZD7Nof0jY4rNdji3DGo9iVuNyGEtOvCdJ1+thzZ2gRsbYwHmeXz2gKAX8AAAAUcm9vdEBERVNLVE9QLUpFRU9CN1IBAgMEBQYH"
    ports:
      - "5000:5000"
    volumes:
      - "./app:/home/app"
    tty: true
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
      - ./config:/data/configdb
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
networks:
  default:
    name: switch_db
    external: true