openapi: "3.0.3"
info:
  title: "tama-connection"
  version: "2.0.0"
servers:
  - url: "http://localhost:5000"
    description: "ローカル環境"
  - url: "http://tama-connect.com/api/"
    description: "本番環境"
tags: 
  - name: "user"
    description: "ユーザーに関する操作"
  - name: "page"
    description: "投稿ページに関する操作"
  - name: "point"
    description: "ポイント(いいねや行ったことがある、行ってみたい)に関する操作"
paths:
  "/"
    get:
      summary: "テスト用"
      tags: []
      deprecated: false
      responses: 
        "200":
          description: "テスト"
          content: 
            "application/json":
              schema:
                type: object
                properties:
                  hello:
                    "Hello World"               
  "/pages"
    get: 
      summary: 投稿されたページを複数取得
      tags: ["page"]
      deprecated: false
      parameters:
        - name: tag
          in: query
          requierd: true
          schema: { type: "kankou" | "gurume" | "omiyage" | "tamasanpo"}
        - name: pageNum
          in: query
          requier: true
          schema: { type: integer}
      responses:
        "200":
          content:
            "application/json"
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      type: object
                      properties:
                        page_id:
                          type: integer
                        title:
                          type: string
                        tag:
                          type: string # kankou or gurume or tamasanpo or omiyage
                        user:
                          type: integer
                        location: 
                          type: object
                          properties:
                            x:
                              type: integer
                            y:
                              type: integer
                        image:
                          type: string # 画像データ(BASE64)
                  max:
                    type: object
                    properties:
                      kankou:
                        type: integer
                      gurume:
                        type: integer
                      tamasanpo:
                        type: tnteger
                      omiyage:
                        type: integer
  "/page/{page_id}"
    get:
      description: 投稿されたページを1つ取得
      tags: ["page"]
      parameters:
        - name: page_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          content:
            "application/json":
              schema:
                type: object
                properties:
                  page_id:
                    type: integer
                  title:
                    type: string
                  tag:
                    type: string # kankou or gurume or tamasanpo or omiyage
                  user:
                    type: integer
                  location: 
                    type: object
                    properties:
                      x:
                        type: number
                      y:
                        type: number
                  image:
                    type: string # 画像データ(BASE64)
        "404":
          description: Article with id {page_id} not found
    delete:
      description: 投稿データの削除
      tags: ["page"]
      parameters:
        - name: page_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description:
          content:
            "application/json":
              schema:
                type: integer # 削除した投稿データのID
        "404":
          description: No delte article {page_id}
  "/page"
    post:
      description: 投稿データの追加
      tags: ["page"]
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string # JWT
      requestBody:
        content:
          application/json:
            schema:
              title:
                type: string
              tag:
                type: string # kankou or gurume or tamasanpo or omiyage
              text:
                type: string
              location_name:
                type: string
              location:
                type: object
                properties:
                  x:
                    type: number
                  y:
                    type: number
              image:
                type: string # base64
  "/map"
    get:
      description: 位置情報の取得
      tags: ["page"]
      parameters:
        - name: myx
          in: query
          required: true
          schema: { type: number }
        - name: myy
          in: query
          required: true
          schema: { type: number }
      responses:
        "200":
          content:
            "application/json":
              schema:
                type: object
                properties:
                  page_count:
                    type: integer
                  locations:
                    type: array
                    items:
                      type: object
                      properties:
                        location:
                          type: object
                          properties:
                            x:
                              type: number
                            y:
                              type: number
                        page_id:
                          type: integer
                  pages:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        tag:
                          type: string # kankou or gurume or tamasanpo or omiyage
                        text:
                          type: string
                        user:
                          type: number
                        location:
                          type: object
                          properties:
                            x:
                              type: number
                            y:
                              type: number
                            distance:
                              type: number
                        image:
                          type: string # base64
                        page_id:
                          type: number
  "/regist"
    post:
      description: ユーザーの登録
      tags: ["user"]
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
      responses:
        "200":
          content:
            "application/json":
              schema:
                type: object
                properties:
                  token:
                    type: string # JWT
  "/login"
    post:
      description: ユーザーのログイン
      tags: ["user"]
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              properties:
                user:
                  type: string
                password:
                  type: string
      responses:
        content:
          "application/json":
            schema:
              type: object
              properties:
                token:
                  type: string # JWT
  "/user"
    get:
      description: ユーザー情報の取得
      tags: ["user"]
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string # JWT
          description: ユーザーID
      responses:
        "200":
          content:
            "application/json":
              schema:
                type: object
                properties:
                  name:
                    type: string
                  checked:
                    type: array
                    items:
                      type: integer
                  files:
                    type: array
                    items:
                      type: integer
  "/users"
    get:
      description: 管理者ならユーザーの登録数を取得する
      tags: ["users"]
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string # JWT
      responses:
        "200":
          content:
            "application/json":
              schema:
                type: int # ユーザー数を返却
    put:
      description: 理者ならばユーザーのパスワードを再設定する
      tags: ["users"]
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string # JWT
      requestBody:
        content:
          application/json:
            schema:
              name:
                type: str
              password:
                type: str
      responses:
        "200":
          description: Changed user password
    delete:
      description: 管理者ならばユーザーを削除する
      tags: ["users"]
      parameters:
        - name: token
          in: header
          required: true
          schema:
            type: string # JWT
      requestBody:
        content:
          application/json:
            schema:
              name:
                type: str
      responses:
        "200":
          description: Success to delete user id {user_id}
  "/point"
    post:
      description: いいねを追加する
      tags: ["point"]
      parameters:
        - name: token
          in: header
          required: true
          shema:
            type: string # JWT
      requestBody:
        description:
        requrred: true
        content:
          application/json:
            shema:
              type: object
              properties:
                page_id: { type: number, example: 1 },
                status: { type: string, example: "good"} # good or go or want
      response:
        "200":
          description: 
          contents:
            application/json:
              shema:
                type: string
    put:
      description: いいねを削除する
      tags: ["point"]
      prameters:
        - name: token
          in: header
          required: true
          shema:
            type: string # JWT
      requestBody:
        description:
        requrred: true
        content:
          application/json:
            shema:
              type: object
              properties:
                page_id: { type: number, example: 1 },
                status: { type: string, example: "good"} # good or go or want
